name-template: $NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: "enhancement"
  - title: 🐛 Bug Fixes
    label: "bug"
  - title: 🛠 Dependency upgrades
    label: "dependencies"
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
