name: "Test Github Actions Environment Variables"
on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-18.04]
        java: [11.0.6]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Groovy 3_0_X
        id: step_three
        run: cd .. && git clone --depth 1 https://github.com/apache/groovy.git -b GROOVY_3_0_X
      - name: List Groovy Dir
        id: step_interm
        run: |
          ls -alrt
          ls -alrt ../
          cd ../groovy
          cat gradle.properties | grep groovyVersion | cut -d\= -f2 |  tr -d '[:space:]'
      - name: Set CI_GROOVY_VERSION for Grails
        id: step_four
        run: |
          cd ../groovy
          echo 'CI_GROOVY_VERSION<<EOF' >> $GITHUB_ENV
          echo "$(cat gradle.properties | grep groovyVersion | cut -d\= -f2 |  tr -d '[:space:]' >> $GITHUB_ENV)" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: echo CI_GROOVY_VERSION
        id: step_five
        run: echo $CI_GROOVY_VERSION
